@startuml
left to right direction
actor Customer

rectangle AIMS {
  Customer --> (View store)
  Customer --> (Update store)
  Customer --> (See current cart)
  (View store) .> (See media details) : include
  (View store) .> (Add media to cart) : extend
  (View store) .> (Play media) : extend
  (See current cart) .> (Filter media in cart) : include
  (See current cart) .> (Sort media in cart) : include
  (See current cart) .> (Remove media from cart) : include
  (See current cart) .> (Place order) : include
  (Update store) .> (Add media) : include
  (Update store) .> (Remove media) : include
}
@enduml
